export const SEED_LISTINGS = [
  {
    id: 'seed-1',
    vendor: 'Leila Restaurant',
    category: 'restaurant',
    title: 'Lebanese Surprise Bag',
    description: 'Mezze, grilled meats, and house-made pita rescued from tonight’s service.',
    originalPrice: 45,
    breakevenPrice: 12,
    discountedPrice: 15,
    quantity: 5,
    pickupStart: '21:00',
    pickupEnd: '22:00',
    delivery: false,
    distanceKm: 1.2,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop',
    createdAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: 'seed-2',
    vendor: 'Paul Bakery',
    category: 'bakery',
    title: 'Pastry Bag',
    description: 'Croissants, pain au chocolat and viennoiseries — fresh today.',
    originalPrice: 60,
    breakevenPrice: 16,
    discountedPrice: 20,
    quantity: 8,
    pickupStart: '20:00',
    pickupEnd: '21:00',
    delivery: true,
    distanceKm: 2.4,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop',
    createdAt: Date.now() - 1000 * 60 * 25,
  },
  {
    id: 'seed-3',
    vendor: 'Monoprix',
    category: 'supermarket',
    title: 'Grocery Rescue Box',
    description: 'A curated mix of fresh produce, dairy and pantry items near best-before.',
    originalPrice: 80,
    breakevenPrice: 20,
    discountedPrice: 25,
    quantity: 12,
    pickupStart: '19:00',
    pickupEnd: '20:00',
    delivery: false,
    distanceKm: 3.8,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop',
    createdAt: Date.now() - 1000 * 60 * 20,
  },
  {
    id: 'seed-4',
    vendor: 'Megu Doha',
    category: 'restaurant',
    title: 'Omakase Sushi Bag',
    description: 'Chef-curated selection of nigiri, maki rolls, and sashimi from tonight’s counter.',
    originalPrice: 95,
    breakevenPrice: 22,
    discountedPrice: 28,
    quantity: 4,
    pickupStart: '22:00',
    pickupEnd: '23:00',
    delivery: true,
    distanceKm: 0.9,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop',
    createdAt: Date.now() - 1000 * 60 * 15,
  },
];
